/* export const environment = {
  production: true,
  urlRaiz: 'https://apilegajo.amorinomoda.com',
  apiUrl: 'https://apilegajo.amorinomoda.com/api/test_api_crud',
  apiUrl2: 'https://apilegajo.amorinomoda.com/api/test_api',
  apiUrl3: 'https://apilegajo.amorinomoda.com/api/file',
  apiUpdateFile: 'https://apilegajo.amorinomoda.com/api/update/upload',
  apiListarFiles: 'https://apilegajo.amorinomoda.com/api/listar/files',
  apiDeleteFile: 'https://apilegajo.amorinomoda.com/api/update/upload',
  apiUrlTrabajador: 'https://apilegajo.amorinomoda.com/api/trabajador',
  apiUrlRegister: 'https://apilegajo.amorinomoda.com/api/register',
  apiUrlLogin: 'https://apilegajo.amorinomoda.com/api/login',
  apiUrlEmail: 'https://apilegajo.amorinomoda.com/api/enviar_correo',
  apiUrlEmpleador: 'https://apilegajo.amorinomoda.com/api/empleador',
  apiUrlUltimoEmpleador:
    'https://apilegajo.amorinomoda.com/api/ultimo_empleador',
  apiUrlActividadUltimoEmpleador:
    'https://apilegajo.amorinomoda.com/api/actividad_ultimo_empleador',
    apiUrlMision: 'https://apilegajo.amorinomoda.com/api/mision',
    apiUrlMisionActualizar: 'https://apilegajo.amorinomoda.com/api/mision/actualizar',
    apiUrlMisionUpdate: 'https://apilegajo.amorinomoda.com/api/mision/update/upload',
    apiUrl3Carousel: 'https://apilegajo.amorinomoda.com/api/carousel/upload',
  apiUpdateFileCarousel: 'https://apilegajo.amorinomoda.com/api/carousel/update/upload',
  apiListarFilesCarousel: 'https://apilegajo.amorinomoda.com/api/carousel/listar/files',
  apiDeleteFileCarousel: 'https://apilegajo.amorinomoda.com/api/carousel/update/upload',
  apiUrl3Producto: 'https://apilegajo.amorinomoda.com/api/productos/subir',
  apiUpdateFileProducto: 'https://apilegajo.amorinomoda.com/api/productos/update',
  apiListarFilesProducto: 'https://apilegajo.amorinomoda.com/api/productos',
  apiListarCursosProducto: 'https://apilegajo.amorinomoda.com/api/productos/cursos',
  apiListarEspecialidadesProducto: 'https://apilegajo.amorinomoda.com/api/productos/especialidades',
  apiDeleteFileProducto: 'https://apilegajo.amorinomoda.com/api/productos',
  apiListarContactos: 'https://apilegajo.amorinomoda.com/api/contactos',
  apiUrl3Testimonio: 'https://apilegajo.amorinomoda.com/api/testimonios/subir',
  apiUpdateFileTestimonio: 'https://apilegajo.amorinomoda.com/api/testimonios/update',
  apiListarFilesTestimonio: 'https://apilegajo.amorinomoda.com/api/testimonios',
  apiDeleteFileTestimonio: 'https://apilegajo.amorinomoda.com/api/testimonios',
  apiUrl3Banner: 'https://apilegajo.amorinomoda.com/api/banners/subir',
  apiUpdateFileBanner: 'https://apilegajo.amorinomoda.com/api/banners/update',
  apiListarFilesBanner: 'https://apilegajo.amorinomoda.com/api/banners',
  apiDeleteFileBanner: 'https://apilegajo.amorinomoda.com/api/banners',
  apiUrl3Slider: 'https://apilegajo.amorinomoda.com/api/sliders/subir',
  apiUpdateFileSlider: 'https://apilegajo.amorinomoda.com/api/sliders/update',
  apiListarFilesSlider: 'https://apilegajo.amorinomoda.com/api/sliders',
  apiDeleteFileSlider: 'https://apilegajo.amorinomoda.com/api/sliders',
}; */

export const environment = {
  production: true,
  urlRaiz: 'https://api.hawatech.agency',
  apiUrl: 'https://api.hawatech.agency/api/test_api_crud',
  apiUrl2: 'https://api.hawatech.agency/api/test_api',
  apiUrl3: 'https://api.hawatech.agency/api/upload',
  apiUpdateFile: 'https://api.hawatech.agency/api/update/upload',
  apiListarFiles: 'https://api.hawatech.agency/api/listar/files',
  apiDeleteFile: 'https://api.hawatech.agency/api/update/upload',
  apiUrlTrabajador: 'https://api.hawatech.agency/api/trabajador',
  apiUrlRegister: 'https://api.hawatech.agency/api/register',
  apiUrlLogin: 'https://api.hawatech.agency/api/login',
  apiUrlEmail: 'https://api.hawatech.agency/api/enviar_correo',
  apiUrlEmpleador: 'https://api.hawatech.agency/api/empleador',
  apiUrlUltimoEmpleador: 'https://api.hawatech.agency/api/ultimo_empleador',
  apiUrlActividadUltimoEmpleador:
    'https://api.hawatech.agency/api/actividad_ultimo_empleador',
  apiUrlMision: 'https://api.hawatech.agency/api/mision',
  apiUrlMisionActualizar: 'https://api.hawatech.agency/api/mision/actualizar',
  apiUrlMisionUpdate: 'https://api.hawatech.agency/api/mision/update/upload',
  apiUrl3Carousel: 'https://api.hawatech.agency/api/carousel/upload',
  apiUpdateFileCarousel:
    'https://api.hawatech.agency/api/carousel/update/upload',
  apiListarFilesCarousel:
    'https://api.hawatech.agency/api/carousel/listar/files',
  apiDeleteFileCarousel:
    'https://api.hawatech.agency/api/carousel/update/upload',
  apiUrl3Producto: 'https://api.hawatech.agency/api/productos/subir',
  apiUpdateFileProducto: 'https://api.hawatech.agency/api/productos/update',
  apiListarFilesProducto: 'https://api.hawatech.agency/api/productos',
  apiListarCursosProducto: 'https://api.hawatech.agency/api/productos/cursos',
  apiListarEspecialidadesProducto:
    'https://api.hawatech.agency/api/productos/especialidades',
  apiDeleteFileProducto: 'https://api.hawatech.agency/api/productos',
  apiListarContactos: 'https://api.hawatech.agency/api/contactos',
  apiUrl3Testimonio: 'https://api.hawatech.agency/api/testimonios/subir',
  apiUpdateFileTestimonio: 'https://api.hawatech.agency/api/testimonios/update',
  apiListarFilesTestimonio: 'https://api.hawatech.agency/api/testimonios',
  apiDeleteFileTestimonio: 'https://api.hawatech.agency/api/testimonios',
  apiUrl3Banner: 'https://api.hawatech.agency/api/banners/subir',
  apiUpdateFileBanner: 'https://api.hawatech.agency/api/banners/update',
  apiListarFilesBanner: 'https://api.hawatech.agency/api/banners',
  apiDeleteFileBanner: 'https://api.hawatech.agency/api/banners',
  apiUrl3Slider: 'https://api.hawatech.agency/api/sliders/subir',
  apiUpdateFileSlider: 'https://api.hawatech.agency/api/sliders/update',
  apiListarFilesSlider: 'https://api.hawatech.agency/api/sliders',
  apiDeleteFileSlider: 'https://api.hawatech.agency/api/sliders',
};
